# Get the scripts requires by the 'clientset' makefile target
required = ["k8s.io/code-generator/cmd/client-gen"]

[prune]
  go-tests = true
  unused-packages = true

  # The following per-project options prevent dep from pruning the files it thinks are unused inside these dependencies.

  # This one is needed to get generate-groups.sh
  [[prune.project]]
      name = "k8s.io/code-generator"
      unused-packages = false

  # This one is needed to get files generate-groups.sh depends on
  [[prune.project]]
      name = "k8s.io/gengo"
      unused-packages = false

[[constraint]]
  version = "1.3.0"
  name = "github.com/gogo/protobuf"

[[override]]
  version = "1.3.2"
  name = "github.com/golang/protobuf"

[[constraint]]
  revision = "ee2393f3bbf04700fc5d611077496c47ec1937ed"
  name = "github.com/ilackarms/protokit"

[[constraint]]
  name = "github.com/solo-io/go-utils"
  version = "0.11.0"

[[constraint]]
  version = ">=0.9.0"
  name = "github.com/envoyproxy/go-control-plane"

[[constraint]]
  version = ">=0.22.1"
  name = "go.opencensus.io"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.2"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.16.2"

# Pin the code-generator to the same version as the k8s libraries we are directly using in our code
[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.16.2"

# Pin gengo to the revision used by the above code-generator version
[[override]]
  name = "k8s.io/gengo"
  revision = "26a664648505d962332bda642b27306bc10d1082"

# xerrors doesn't have a version. this is needed to work with go 1.13
[[override]]
  revision = "a985d3407aa71f30cf86696ee0a2f409709f22e1"
  name = "golang.org/x/xerrors"
